  
  USE A_Qiancy


  GO 
   ALTER TABLE AA01交通水利用地图斑2014 ADD CONSTRAINT PRIMARY_AA01_OBJECTID PRIMARY KEY(OBJECTID)
   
   GO 
   CREATE  INDEX INDEX_AA01_ifq ON AA01交通水利用地图斑2014(ifq)
   
   GO
   
   ALTER TABLE AB02非建设用地图斑2009 ADD CONSTRAINT PRIMARY_B02_OBJECTID PRIMARY KEY(OBJECTID)
   

GO
  --创建控件索引
  CREATE SPATIAL INDEX INDEX_AA01_SHAPE 
  ON [A_Qiancy].[dbo].AA01交通水利用地图斑2014(SHAPE)
  USING GEOMETRY_AUTO_GRID 
  WITH ( BOUNDING_BOX = (6000,10000,100000,102000) )
  
  GO
  
   CREATE SPATIAL INDEX INDEX_AB02_SHAPE 
  ON [A_Qiancy].[dbo].AB02非建设用地图斑2009(SHAPE)
  USING GEOMETRY_AUTO_GRID 
  WITH ( BOUNDING_BOX = (6000,10000,100000,102000) )
  
  
  GO
  --创建结果表
  CREATE TABLE T_Result(
	[AID] [int] NOT NULL,
	[BID] [int] NOT NULL,
	[AREA] [float] NULL,
 CONSTRAINT [PK_T_Result] PRIMARY KEY CLUSTERED 
(
	[AID] ASC,
	[BID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
  

